server.port: 8080

# minio properties
minio:
  endpoint: minio-host:9000
  bucket: tracks
  access-key: music_metadata
  secret-key: music_metadata

spring:
  datasource:
    url: "jdbc:postgresql://postgres:5432/postgres?currentSchema=music_metadata,public"
    username: "music_metadata"
    password: "music_metadata"
    driver-class-name: "org.postgresql.Driver"

  liquibase:
    enabled: true
    database-change-log-lock-table: "databasechangeloglock"
    database-change-log-table: "databasechangelog"
    change-log: "classpath:db/changelog-master.yaml"
    default-schema: "music_metadata"
    url: "jdbc:postgresql://postgres:5432/postgres?currentSchema=music_metadata,public"
    user: "music_metadata"
    password: "music_metadata"