version: '2'
services:
  postgres:
    image: "postgres:14.1"
    volumes:
      - ./dev/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432