version: '3'
services:
  postgres:
    image: "postgres:14.1"
    volumes:
      - ./dev/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: music_metadata
      MINIO_ROOT_PASSWORD: music_metadata
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 music_metadata music_metadata;
      /usr/bin/mc mb myminio/tracks;
      /usr/bin/mc policy set public myminio/tracks;
      exit 0;
      "
volumes:
  minio_storage: { }